name: Deploy Workflows

on: [push]

jobs:
  deploy-workflows:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Deploy Workflows
        uses: jwulf/zeebe-action@master
        with:
          clientConfig: ${{ secrets.ZEEBE_CLIENT_CONFIG }}
          operation: deployWorkflow
          bpmnDirectory: .
      - name: CreateWorkflowInstance
        uses: jwulf/zeebe-action@master
        with:
          operation: createWorkflowInstance
          bpmnProcessId: Test_Yolo_workflow
      - name: Start Workers
        uses: jwulf/zeebe-action@master
        with:
          operation: startWorkers
          workerHandlerFile: cloud-workers.js  
          workerLifetimeMins: 0.2  
       

